name: Robot Framework CI

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Rodar auditoria estática (Robocop)
        run: |
          echo "Relatório gerado em: $(date '+%Y-%m-%d %H:%M:%S')"
          robocop .

      - name: Rodar Testes Web (Headless Mode)
        run: |
          # Rodando browser no modo headless
          robot -d ./results/web -v BROWSER:headlesschrome -l log_web.html -r report_web.html tests/web

      - name: Rodar Testes de API (ServeRest)
        run: |
          robot -d ./results/api -l log_api.html -r report_api.html tests/api

      - name: Upload dos Resultados e Prints
        if: always() # Garante o upload mesmo se o teste falhar
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-do-teste
          path: ./results/